/**
 * Device Register Table
 */
CREATE TABLE cc_card
(
    id                  BIGINT                                       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    creationdate        TIMESTAMP      DEFAULT current_timestamp()   NOT NULL,
    firstusedate        TIMESTAMP                                    NULL,
    expirationdate      TIMESTAMP      DEFAULT '0000-00-00 00:00:00' NOT NULL,
    username            VARCHAR(50)                                  NOT NULL,
    iccid_card          VARCHAR(100)                                 NULL,
    imsi_card           VARCHAR(100)                                 NULL,
    useralias           VARCHAR(50)                                  NOT NULL,
    uipass              VARCHAR(50)                                  NOT NULL,
    generic_id          VARCHAR(50)                                  NULL,
    credit              DECIMAL(15, 5) DEFAULT 0.00000               NOT NULL,
    activated           CHAR           DEFAULT 'f'                   NOT NULL,
    status              INT            DEFAULT 1                     NOT NULL,
    lastname            VARCHAR(50)                                  NOT NULL,
    firstname           VARCHAR(50)                                  NOT NULL,
    address             VARCHAR(100)                                 NOT NULL,
    city                VARCHAR(40)                                  NOT NULL,
    state               VARCHAR(40)                                  NOT NULL,
    country             VARCHAR(40)                                  NOT NULL,
    zipcode             VARCHAR(20)                                  NOT NULL,
    phone               VARCHAR(20)                                  NOT NULL,
    email               VARCHAR(70)                                  NOT NULL,
    fax                 VARCHAR(20)                                  NOT NULL,
    inuse               INT            DEFAULT 0                     NULL,
    tipo                VARCHAR(10)                                  NOT NULL,
    apn                 VARCHAR(30)                                  NOT NULL,
    nas_ip              VARCHAR(18)                                  NOT NULL,
    lac                 VARCHAR(10)                                  NOT NULL,
    currency            CHAR(3)        DEFAULT 'USD'                 NULL,
    lastuse             TIMESTAMP      DEFAULT '0000-00-00 00:00:00' NOT NULL,
    stoptime            TIMESTAMP      DEFAULT current_timestamp()   NOT NULL,
    nbused              INT            DEFAULT 0                     NULL,
    typepaid            INT            DEFAULT 0                     NULL,
    creditlimit         DECIMAL(15, 5) DEFAULT 0.00000               NULL,
    language            CHAR(5)        DEFAULT 'en'                  NULL,
    redial              VARCHAR(50)                                  NOT NULL,
    num_trials_done     BIGINT         DEFAULT 0                     NULL,
    num_trials_donerx   BIGINT                                       NULL COMMENT 'credit limit download messages',
    vat                 FLOAT          DEFAULT 0                     NOT NULL,
    servicelastrun      TIMESTAMP      DEFAULT current_timestamp()   NOT NULL,
    initialbalance      DECIMAL(15, 5) DEFAULT 0.00000               NOT NULL,
    databytes           BIGINT         DEFAULT 0                     NOT NULL COMMENT 'data in bytes for Kite',
    invoiceday          INT            DEFAULT 1                     NULL,
    autorefill          INT            DEFAULT 0                     NULL,
    loginkey            VARCHAR(40)                                  NOT NULL,
    mac_addr            CHAR(200)      DEFAULT '00-00-00-00-00-00'   NOT NULL,
    checkimei           SMALLINT       DEFAULT 0                     NOT NULL COMMENT 'Auth to validate IMEI of connected device',
    fenceradius         DECIMAL(10, 5) DEFAULT 0.00000               NOT NULL COMMENT 'Radius in Kms from geo center',
    tag                 VARCHAR(50)                                  NOT NULL,
    voicemail_permitted INT            DEFAULT 0                     NOT NULL,
    last_notification   TIMESTAMP                                    NULL,
    email_notification  VARCHAR(70)                                  NOT NULL,
    notify_email        SMALLINT       DEFAULT 0                     NOT NULL,
    credit_notification DECIMAL(15, 5) DEFAULT -1.00000              NOT NULL,
    id_group            INT            DEFAULT 1                     NOT NULL,
    company_name        VARCHAR(50)                                  NOT NULL,
    traffic             BIGINT                                       NULL,
    traffic_target      VARCHAR(500)                                 NULL,
    planid              BIGINT                                       NULL COMMENT 'plans.id reference',
    plandesc            VARCHAR(50)    DEFAULT ''                    NOT NULL COMMENT 'plan description',
    discount            DECIMAL(15, 2) DEFAULT 0.00                  NOT NULL,
    arc                 DECIMAL(15, 2) DEFAULT 0.00                  NOT NULL COMMENT 'Annual Recurring Cost',
    instfee             DECIMAL(15, 2) DEFAULT 0.00                  NOT NULL,
    cancelfee           DECIMAL(15, 2) DEFAULT 0.00                  NOT NULL,
    overage             DECIMAL(15, 5) DEFAULT 0.00000               NOT NULL COMMENT 'overage cost per meg or 10k iot hits',
    wsalemrc            DECIMAL(15, 2) DEFAULT 0.00                  NOT NULL COMMENT 'wholesale mrc',
    restriction         TINYINT        DEFAULT 0                     NOT NULL,
    id_seria            INT                                          NULL COMMENT '0=blocked. 1=active in remote API partner',
    serial              BIGINT                                       NULL,
    serialrx            BIGINT                                       NULL COMMENT 'max # download messages',
    block               INT            DEFAULT 0                     NOT NULL,
    sessionid           VARCHAR(40)                                  NOT NULL,
    status_type         VARCHAR(30)                                  NOT NULL,
    ip                  VARCHAR(50)                                  NULL COMMENT 'Assigned by Accounting Packet',
    framed_ip           VARCHAR(50)                                  NULL COMMENT 'Assigned fixed IP by application',
    iccid               VARCHAR(50)                                  NULL,
    imsi                VARCHAR(50)                                  NULL,
    ip1                 VARCHAR(30)                                  NULL,
    nas1                VARCHAR(30)                                  NULL,
    ip2                 VARCHAR(30)                                  NULL,
    nas2                VARCHAR(30)                                  NULL,
    dns_prim            VARCHAR(30)                                  NULL COMMENT 'Primary DNS',
    dns_sec             VARCHAR(30)                                  NULL COMMENT 'Secondary DNS',
    block_ip            VARCHAR(30)                                  NULL COMMENT 'used to redirect auth rejects to a blocked IP',
    imei                VARCHAR(50)                                  NULL,
    cellid              VARCHAR(50)                                  NULL,
    lat                 VARCHAR(50)                                  NOT NULL,
    `long`              VARCHAR(50)                                  NOT NULL,
    mcc                 VARCHAR(15)                                  NOT NULL,
    mnc                 VARCHAR(15)                                  NOT NULL,
    erb                 VARCHAR(15)    DEFAULT ''                    NOT NULL,
    upload              INT            DEFAULT 0                     NULL COMMENT 'session upload in BYTES',
    download            INT            DEFAULT 0                     NOT NULL COMMENT 'Session download in BYTES',
    last_upload         INT            DEFAULT 0                     NOT NULL,
    last_download       INT            DEFAULT 0                     NOT NULL,
    tx                  DOUBLE                                       NOT NULL,
    rx                  DOUBLE                                       NOT NULL,
    grandtotal          DECIMAL(25, 5) DEFAULT 0.00000               NOT NULL COMMENT 'Accumulated total traffic since creation in MB',
    rat_type            VARCHAR(20)                                  NULL,
    qosprofile          VARCHAR(30)                                  NULL,
    sessiontime         VARCHAR(30)                                  NOT NULL,
    eventtime           DATETIME                                     NOT NULL,
    termcause           VARCHAR(30)                                  NULL,
    accton              TINYINT(1)     DEFAULT 0                     NOT NULL COMMENT 'Accounting updated',
    payload             VARCHAR(3000)                                NULL,
    updated             TIMESTAMP      DEFAULT current_timestamp()   NOT NULL on update current_timestamp() COMMENT 'TIMESTAMP when the record was touched',
    CONSTRAINT uq_cc_card_useralias UNIQUE (useralias),
    CONSTRAINT uq_cc_card_username UNIQUE (username)
);

/**
 * Device Account Table
 */
CREATE TABLE radacct
(
    radacctid            BIGINT                                     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    acctsessionid        VARCHAR(64)    DEFAULT ''                  NOT NULL,
    acctuniqueid         VARCHAR(64)                                NULL,
    username             VARCHAR(64)    DEFAULT ''                  NOT NULL,
    groupname            VARCHAR(64)    DEFAULT ''                  NOT NULL,
    realm                VARCHAR(64)    DEFAULT ''                  NULL,
    nasipaddress         VARCHAR(15)    DEFAULT ''                  NOT NULL,
    nasportid            VARCHAR(15)                                NULL,
    nasporttype          VARCHAR(32)                                NULL,
    acctstarttime        DATETIME                                   NULL,
    acctstoptime         DATETIME                                   NULL,
    acctupdatetime       DATETIME                                   NULL,
    acctinterval         INT(20)                                    NULL,
    acctsessiontime      INT(12)                                    NULL,
    acctauthentic        VARCHAR(32)                                NULL,
    connectinfo_start    VARCHAR(50)                                NULL,
    connectinfo_stop     VARCHAR(50)                                NULL,
    acctinputoctets      BIGINT                                     NULL,
    acctoutputoctets     BIGINT                                     NULL,
    calledstationid      VARCHAR(50)    DEFAULT ''                  NOT NULL,
    callingstationid     VARCHAR(50)    DEFAULT ''                  NOT NULL,
    cellid               VARCHAR(50)                                NOT NULL,
    imsi                 VARCHAR(30)    DEFAULT ''                  NOT NULL,
    imei                 VARCHAR(50)                                NULL,
    acctterminatecause   VARCHAR(32)    DEFAULT ''                  NOT NULL,
    servicetype          VARCHAR(32)                                NULL,
    framedprotocol       VARCHAR(32)                                NULL,
    framedipaddress      VARCHAR(15)    DEFAULT ''                  NOT NULL,
    acctstartdelay       INT(12)                                    NULL,
    acctstopdelay        INT(12)                                    NULL,
    xascendsessionsvrkey VARCHAR(10)                                NULL,
    last_chk_octets      BIGINT         DEFAULT 0                   NOT NULL,
    last_chk_datetime    DATETIME                                   NULL,
    last_chk_all_done    tinyINT(1)     DEFAULT 0                   NOT NULL,
    dupe                 tinyINT(1)     DEFAULT 0                   NOT NULL,
    datausage            decimal(15, 5) DEFAULT 0.00000             NULL,
    sessionbill          decimal(15, 5) DEFAULT 0.00000             NOT NULL,
    terminatecauseid     INT(1)         DEFAULT 1                   NULL,
    card_id              BIGINT                                     NOT NULL,
    last_updated         TIMESTAMP      DEFAULT current_timestamp() NOT NULL on update current_timestamp(),
    CONSTRAINT uq_radacct_radacctid UNIQUE (acctuniqueid)
);